apiVersion: v1
kind: ConfigMap
metadata:
  name: lumina-integration-config
  namespace: lumina-ai
data:
  service_dependencies: '{
    "enduser-service": ["testing-environment", "export-system"],
    "testing-environment": [],
    "export-system": []
  }'
  integration_endpoints: '{
    "enduser-service": {
      "testing": "/api/v1/testing",
      "export": "/api/v1/export"
    },
    "testing-environment": {
      "create": "/api/v1/sandbox/create",
      "execute": "/api/v1/sandbox/execute",
      "status": "/api/v1/sandbox/status",
      "terminate": "/api/v1/sandbox/terminate"
    },
    "export-system": {
      "formats": "/api/v1/formats",
      "export": "/api/v1/export",
      "status": "/api/v1/status",
      "download": "/api/v1/download"
    }
  }'
  feature_integration: '{
    "projects": {
      "enabled": true,
      "services": ["enduser-service"]
    },
    "operator-window": {
      "enabled": true,
      "services": ["enduser-service"]
    },
    "visual-thinking": {
      "enabled": true,
      "services": ["enduser-service"]
    },
    "memory-tracking": {
      "enabled": true,
      "services": ["enduser-service"]
    },
    "testing-environment": {
      "enabled": true,
      "services": ["enduser-service", "testing-environment"]
    },
    "export-system": {
      "enabled": true,
      "services": ["enduser-service", "export-system"]
    }
  }'
