apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-service
  namespace: lumina-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider-service
  template:
    metadata:
      labels:
        app: provider-service
    spec:
      containers:
      - name: provider-service
        image: ${PROVIDER_SERVICE_IMAGE}
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: db_url
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: db_username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: db_password
        - name: PROVIDER_API_KEYS
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: provider_api_keys
---
apiVersion: v1
kind: Service
metadata:
  name: provider-service
  namespace: lumina-ai
spec:
  selector:
    app: provider-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
